# Generated by Django 3.2.3 on 2021-06-07 18:17
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='дата последней правки')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description_brief', models.CharField(blank=True, default='', max_length=256, verbose_name='краткое опиание')),
                ('description_full', models.TextField(blank=True, default='', verbose_name='история')),
                ('file', models.FileField(blank=True, upload_to='projects/uploads', verbose_name='docs')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('curators', models.ManyToManyField(blank=True, related_name='project_curators', to=settings.AUTH_USER_MODEL, verbose_name='curators')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
    ]
