# Generated by Django 3.2.3 on 2021-06-07 20:01
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20210607_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='project',
            name='curators',
            field=models.ManyToManyField(blank=True, related_name='project_curators', to=settings.AUTH_USER_MODEL, verbose_name='Кураторы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_brief',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_full',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Редактировал'),
        ),
    ]
