# Generated by Django 3.2.4 on 2021-06-24 13:43
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('jp', models.BooleanField(default=False)),
                ('inn', models.CharField(blank=True, default='', max_length=10)),
                ('kpp', models.CharField(blank=True, default='', max_length=25)),
                ('okpo', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='', max_length=15)),
            ],
            options={
                'verbose_name': ('Заказчик',),
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=33)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_contracts', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=35)),
                ('bic', models.TextField(default='', max_length=32)),
                ('account', models.TextField(default='', max_length=30)),
                ('c_account', models.TextField(default='', max_length=28)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bank', to='customer.customer')),
            ],
            options={
                'verbose_name': ('Реквизиты',),
                'verbose_name_plural': 'Перечень реквизитов',
            },
        ),
    ]
