# Generated by Django 3.2.4 on 2021-06-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='account',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='bic',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='c_account',
            field=models.CharField(default='', max_length=28),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='name',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='name',
            field=models.CharField(default='', max_length=33),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=35),
        ),
    ]
