# Generated by Django 3.2.4 on 2021-06-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210624_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='jp',
            field=models.CharField(choices=[('FP', 'Физлицо'), ('JP', 'ООО')], max_length=3),
        ),
    ]
