# Generated by Django 3.2.4 on 2021-06-24 13:43
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('specs', models.JSONField()),
                ('note', models.CharField(max_length=100)),
                ('avg_delivery_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specs', models.JSONField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contracts', to='customer.contracts')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectCurators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_curator', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectConsumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables_project', to='project.consumables')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_consumables', to='project.project')),
            ],
        ),
    ]
