# Generated by Django 3.2.4 on 2021-06-24 14:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconsumables',
            name='quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
