# Generated by Django 3.2.3 on 2021-06-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210608_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocs',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='projects/upload'),
        ),
    ]
